<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-3BHS2BP" name="Tests.UserLoginTests" tests="4" failures="1" timestamp="2021-02-12T00:12:05 CST" time="37.725" errors="0">
  <testcase name="ManagerLoginTest" time="9.600" classname="Tests.UserLoginTests"/>
  <system-out/>
  <testcase name="ClientLoginTest" time="11.256" classname="Tests.UserLoginTests"/>
  <system-out/>
  <testcase name="DesignerLoginTest" time="7.208" classname="Tests.UserLoginTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusablemethods.ActionEngine.assertEqualsString_custom(ActionEngine.java:113)
at Tests.UserLoginTests.DesignerLoginTest(UserLoginTests.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- DesignerLoginTest -->
  <system-out/>
  <testcase name="DesignerLoginTest" time="9.661" classname="Tests.UserLoginTests">
    <skipped/>
  </testcase> <!-- DesignerLoginTest -->
  <system-out/>
</testsuite> <!-- Tests.UserLoginTests -->
